### ISSUE TITLE
[OniMcp] Keep 2025 initialize-era revisions out of server/discover

### ISSUE THREAD

**Issue by LIghtJUNction** [LIghtJUNction/OniMods#482]
## Problem

The current `server/discover` success response advertises `2026-07-28`, `2025-11-25`, and `2025-06-18` in `supportedVersions`.

That mixes the modern discovery era with the intentionally retained 2025 `initialize`/session compatibility path. Current official MCP SDK behavior separates them: successful modern discovery advertises modern revisions, while 2025-era revisions are negotiated through `initialize`.

This was introduced by #462 from #461. Fresh review of the current official Tier-1 SDK/spec behavior shows that interpretation should be corrected rather than propagated.

## User-visible risk

A modern client can treat a successfully advertised 2025 revision as a valid post-discovery choice even though OniMcp keeps 2025 on the legacy initialize/session path. Advertising a protocol revision on a path that does not implement that revision's lifecycle creates avoidable interoperability failures.

## Acceptance

- successful `server/discover` advertises only the actually implemented modern revision (`2026-07-28`)
- unsupported modern-protocol errors advertise the same modern-only supported set
- existing 2025 `initialize`/session compatibility remains unchanged
- raw loopback/final-wire discovery regression passes
- modern protocol and Python contract/smoke coverage passes
- `git diff --check` and current OniMcp reference CI pass
- no game-write/runtime behavior is changed; this is transport negotiation before ONI dispatch
